# Generated by Django 5.1.1 on 2024-10-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('risk', models.CharField(choices=[('high', 'High'), ('low', 'Low'), ('inconclusive', 'Inconclusive')], default='inconclusive', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('risk_categories', models.ManyToManyField(related_name='genes', to='genes.disease')),
            ],
        ),
    ]
