# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=88]

  - repo: local
    hooks:
      - id: run-tests
        name: Run test cases
        entry: pytest
        language: system
        types: [python]

      - id: run-linter
        name: Run linter
        entry: flake8
        language: system
        types: [python]
